services:

  postgres:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

  app:
    image: ars
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '12345:8080'
    
  db-updater:
    image: ars-db-updater
    build:
      context: .
      dockerfile: Dockerfile.db-updater

volumes:
  postgres-data: