services:

  postgres:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: %DB_PASSWORD%
    ports:
      - 5432:5432
    volumes:
      - %DB_VOLUME%

  app:
    image: ars
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080

volumes:
  postgres-data: