FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["ARS.csproj", "./"]
COPY . .
RUN dotnet tool install --create-manifest-if-needed dotnet-ef
ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh wait-for-it.sh
RUN chmod +x wait-for-it.sh
RUN echo './wait-for-it.sh postgres:5432 --timeout=60 && dotnet ef database update' > db-updater.sh
RUN chmod +x db-updater.sh
ENTRYPOINT ["bash", "db-updater.sh"]