services:

  postgres:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: %DB_PASSWORD%
    ports:
      - 64205:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: ars
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 64208:8080
  
  prometheus:
    image: prom/prometheus
    restart: on-failure
    ports:
      - 64209:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
#    environment:
#      - GF_SERVER_ROOT_URL=http://localhost:64203/grafana
#      - GF_INSTALL_PLUGINS=grafana-clock-panel
    ports:
      - 64203:3000
    volumes:
      - 'grafana-data:/var/lib/grafana'

volumes:
  postgres-data: {}
  prometheus-data: {}
  grafana-data: {}