entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsEncrypt:
    acme:
      email: kiriakov.f.m@gmail.com
      storage: acme.json
      tlsChallenge: { }

api:
  dashboard: true