entryPoints:
  web:
    address: :80
  websecure:
    address: :443
    
http:
  middlewares:
    websecureRedirect:
      redirectScheme:
        scheme: https
        permanent: true

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsEncrypt:
    acme:
      email: kiriakov.f.m@gmail.com
      storage: acme.json
      tlsChallenge: { }

api:
  dashboard: true