name: Compose Down

on:
  workflow_dispatch:

jobs:

  compose-down:

    runs-on: self-hosted

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compose down
        run: "docker compose down"