name: Compose Up

on:
  push:
    branches: [ "master", "dev" ]

  workflow_dispatch:

jobs:

  compose-up:

    runs-on: self-hosted

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Load app settings
      run: "echo '${{ secrets.SECRETS }}' > secrets.json && chmod +x generator.sh && ./generator.sh remote"

    - name: Compose up
      run: "docker compose up --build -d"