name: Compose Up

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:

  compose-up:

    runs-on: self-hosted

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Load app settings
      run: "echo '${{ secrets.APP_SETTINGS }}' > appsettings.json"

    - name: Compose up
      run: "docker compose up --build -d"