name: CI/CD

on:
  push:
    branches: [ "master" ]
  
  workflow_dispatch:

jobs:

  CI-CD:

    runs-on: self-hosted

    steps:
    
    - name: Kill an existing container
      run: docker container kill ars

    - name: Remove old container
      run: docker container prune -f
    
    - uses: actions/checkout@v3
    - name: Build a new image
      run: docker build . --file Dockerfile --tag ars

    - name: Run the Docker image in a new container
      run: docker run -p 8080:80 --name ars -d ars

    - name: Remove unused images
      run: docker image prune -f
