name: Init CI/CD

on:

  workflow_dispatch:

jobs:

  CI-CD:

    runs-on: self-hosted

    steps:

    - uses: actions/checkout@v3
    - name: Build a new image
      run: docker build . --file Dockerfile --tag allrensys

    - name: Run the Docker image in a new container
      run: docker run -d allrensys

    - name: Remove unused images
      run: docker image prune -f
