name: CI/CD

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:

  CI-CD:

    runs-on: self-hosted

    steps:

    - uses: actions/checkout@v3
    - name: Compose up
      run: "docker compose up --build -d"