name: Init CI/CD

on:
  push:
    branches: [ "master" ]
  
  workflow_dispatch:

jobs:

  CI-CD:

    runs-on: self-hosted

    steps:

    - uses: actions/checkout@v3
    - name: Build a new image
      run: docker build . --file Dockerfile --tag ars

    - name: Run the Docker image in a new container
      run: docker run --name ars -d ars

    - name: Remove unused images
      run: docker image prune -f
